const express = require('express');
const { createUser } = require('../controller/userController');
const { loginUser } = require('../controller/userController');
const { getUsers } = require('../controller/userController');
const { getaUser } = require('../controller/userController');
const { deleteUser } = require('../controller/userController');
const { updateUser } = require('../controller/userController');
const { blockUser } = require('../controller/userController');
const { unblockUser } = require('../controller/userController');
const {authMiddleware,isAdmin} = require('../middleware/authMiddleware');
const router = express.Router();

router.post('/register',createUser);
router.post('/login',loginUser);
router.get('/users',getUsers);
router.get('/user/:id',authMiddleware,isAdmin,getaUser);
router.delete('/delete/:id',deleteUser);
router.patch('/update/:id',updateUser);
router.patch('/block/:id',authMiddleware,isAdmin,blockUser);
router.patch('/unblock/:id',authMiddleware,isAdmin,unblockUser);
module.exports = router;